<?php
$arr = array('Marca' => array('Fiat','VW','Ford','GM'),
    'Modelo' => array('147','Fusca','GT40','Camaro'),
    'Ano' => array('1998','1983','2000','2018'));

echo '<table class="table">';
echo'<thead class="thead-dark">';
echo'<tr>';

foreach ($arr as $chave => $valor ){
    echo'<th scope="col">'.$chave.'</th>';
}
echo'</tr>';
echo'</thead>';

echo '<tbody>';

echo '<tr>';

foreach ($arr as $chave => $valor){
    echo '<td>';
        foreach ($valor as $chave2 => $dados){
            echo $dados;
            echo '<hr>';
            echo '<br>';
    }
        echo '</td>';
}
echo '</tr>';


echo '</tbody>';
echo '</table>';


?>