<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>..: Exemplo MVC :..</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="Public/css/bootstrap.css">
    <link rel="stylesheet" href="Public/css/style.css">
</head>
<body>
<div class="container-fluid">
    <h1>Topo</h1>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Dev</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample07">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#servicos">Serviços</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Empresa">Descrição</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contato">Contato</a>
                    </li>

                </ul>

            </div>
        </div>
    </nav>
    <?php
        echo $this->content();
    ?>
    <h1>Rodapé</h1>
</div>
    <div class="jumbotron rodape">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-4">
                    <h5>Dev</h5>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#inicio" class="link-rodape">Home</a>
                        </li>
                        <li>
                            <a href="#servicos" class="link-rodape">Serviço</a>
                        </li>
                        <li>
                            <a href="#descricao" class="link-rodape">Descrição</a>
                        </li>
                        <li>
                            <a href="#contato" class="link-rodape">Contato</a>
                        </li>
                    </ul>
                </div>
                <div class="col-12 col-sm-12 col-md-4">
                    <h5>Contato</h5>
                    <ul class="list-unstyled">
                        <li>
                            <a href="tel: XXXXXXXXXXX" class="link-rodape">(XX) XXXXX-XXXX</a>
                        </li>
                        <li>
                            <a href="#contato" class="link-rodape">Av. Goiania</a>
                        </li>
                        <li>
                            <a href="#contato" class="link-rodape">CNPJ: XX.XXX.XXX/XXXX-XX</a>
                        </li>
                    </ul>
                </div>
                <div class="col-12 col-sm-12 col-md-4">
                    <h5>Redes Sociais</h5>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#inicio" target="_blank" class="link-rodape">Instagram</a>
                        </li>
                        <li>
                            <a href="#servicos" target="_blank" class="link-rodape">Facebook</a>
                        </li>
                        <li>
                            <a href="#descricao" target="_blank" class="link-rodape">Youtube</a>
                        </li>
                        <li>
                            <a href="#contato" target="_blank" class="link-rodape">Twiter</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>